import '@testing-library/jest-dom/vitest'
import { vi } from 'vitest'

// Mock language provider with English translations as default
const englishTranslations: Record<string, string> = {
  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.cancel': 'Cancel',
  'common.continue': 'Continue',
  'common.save': 'Save',
  'common.back': 'Back',
  'common.questions': 'Questions',
  'common.progress': 'Progress',
  'common.accuracy': 'Accuracy',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.totalQuestionsAnswered': 'Total Questions Answered',
  'dashboard.correctAnswers': 'Correct Answers',
  'dashboard.overallAccuracy': 'Overall Accuracy',
  'dashboard.examsStarted': 'Exams Started',
  'dashboard.recentActivity': 'Recent Activity',
  'dashboard.noHistory': 'No practice history yet. Start an exam to see your stats!',
  'dashboard.allExams': 'All Available Exams',
  'dashboard.loadingExams': 'Loading exams...',
  'dashboard.syncPromptTitle': 'Sign in to sync your learning progress',
  'dashboard.syncPromptDesc': 'Sign in to automatically sync practice progress across your devices.',
  'dashboard.lastStudied': 'Last studied',

  // Exams list
  'exams.myExams': 'My Exams',
  'exams.noExams': 'No exams yet',
  'exams.noExamsDesc': "You haven't joined any exams yet. Go to the dashboard to explore and join exams.",
  'exams.goToDashboard': 'Go to Dashboard',

  // Exam details
  'examDetails.join': 'Join Exam',
  'examDetails.joined': 'Joined',
  'examDetails.practice': 'Practice',
  'examDetails.study': 'Study',
  'examDetails.exam': 'Exam',
  'examDetails.questionsAnswered': 'Questions Answered',
  'examDetails.correctRate': 'Correct Rate',
  'examDetails.bookmarked': 'Bookmarked',
  'examDetails.mistakes': 'Mistakes',
  'examDetails.startExam': 'Start Exam',
  'examDetails.examSettings': 'Exam Settings',
  'examDetails.numberOfQuestions': 'Number of Questions',
  'examDetails.randomSeed': 'Random Seed (Optional)',
  'examDetails.startExamBtn': 'Start Exam',
  'examDetails.loadingExam': 'Loading exam…',
  'examDetails.addedToMyExams': 'Exam added to My Exams',

  // Practice mode
  'practice.title': 'Practice',
  'practice.myMistakes': 'My Mistakes',
  'practice.myBookmarks': 'My Bookmarks',
  'practice.question': 'Question',
  'practice.of': 'of',
  'practice.single': 'Single',
  'practice.multiple': 'Multiple',
  'practice.submitAnswer': 'Submit Answer',
  'practice.correctAnswer': 'Correct Answer!',
  'practice.incorrectAnswer': 'Incorrect Answer',
  'practice.correct': 'Correct Answer',
  'practice.yourAnswer': 'Your Answer',
  'practice.explanation': 'Explanation',
  'practice.loadingQuestions': 'Loading questions…',
  'practice.noMistakes': 'No mistakes to review!',
  'practice.noMistakesDesc': "Great job! You don't have any incorrect answers yet.",
  'practice.noBookmarks': 'No bookmarked questions!',
  'practice.noBookmarksDesc': 'Bookmark questions while practicing to review them here later.',
  'practice.backToExam': 'Back to Exam',
  'practice.clearProgress': 'Clear Progress',
  'practice.clearProgressTitle': 'Are you absolutely sure?',
  'practice.clearProgressDesc': 'This action cannot be undone. This will permanently delete your progress for this exam.',
  'practice.graduated': 'Great job! This question has been removed from My Mistakes.',
  'practice.graduatedDesc': 'You answered it correctly {count} times in a row.',
  'practice.savedLocally': 'Saved locally. Sign in to sync to cloud',
  'practice.bookmarkSavedLocally': 'Bookmark saved locally. Sign in to sync to cloud',

  // Study mode
  'study.title': 'Study Mode',
  'study.showAnswer': 'Show Answer',

  // Exam mode
  'exam.title': 'Exam Mode',
  'exam.timeRemaining': 'Time Remaining',
  'exam.submit': 'Submit Exam',
  'exam.results': 'Exam Results',
  'exam.score': 'Score',
  'exam.passed': 'Passed',
  'exam.failed': 'Failed',

  // Settings
  'settings.title': 'Settings',
  'settings.description': 'Manage your account settings and set e-mail preferences.',
  'settings.profile': 'Profile',
  'settings.account': 'Account',
  'settings.appearance': 'Appearance',

  // Navigation
  'nav.exams': 'Exams',
  'nav.settings': 'Settings',
  'nav.account': 'Account',
  'nav.signIn': 'Sign in',
  'nav.signOut': 'Sign out',

  // Language selector
  'language.select': 'Language',
  'language.en': 'English',
  'language.zh': '简体中文',
  'language.zh-TW': '繁體中文',
  'language.ja': '日本語',

  // Sidebar
  'sidebar.appTitle': 'Question King',
  'sidebar.general': 'General',
  'sidebar.dashboard': 'Dashboard',
  'sidebar.myExams': 'My Exams',
  'sidebar.other': 'Other',
  'sidebar.helpCenter': 'Help Center',

  // Authentication
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.emailPlaceholder': 'name@example.com',
  'auth.passwordPlaceholder': '********',
  'auth.forgotPassword': 'Forgot password?',
  'auth.signInWithEmail': 'Sign In with Email',
  'auth.signUpWithEmail': 'Sign Up with Email',
  'auth.orContinueWith': 'Or continue with',
  'auth.google': 'Google',
  'auth.sendResetLink': 'Send Reset Link',
  'auth.otpLabel': 'One-Time Password',
  'auth.verify': 'Verify',
  'auth.enterEmail': 'Please enter your email',
  'auth.enterPassword': 'Please enter your password',
  'auth.passwordMinLength': 'Password must be at least 7 characters long',
  'auth.confirmPasswordRequired': 'Please confirm your password',
  'auth.passwordsNoMatch': "Passwords don't match.",
  'auth.enterOtp': 'Please enter the 6-digit code.',
  'auth.welcomeBack': 'Welcome back!',
  'auth.signInFailed': 'Failed to sign in',
  'auth.signInGoogleSuccess': 'Signed in with Google successfully!',
  'auth.signInGoogleFailed': 'Failed to sign in with Google',
  'auth.accountCreated': 'Account created successfully!',
  'auth.accountCreateFailed': 'Failed to create account',
  'auth.resetEmailSent': 'Password reset email sent',
  'auth.resetEmailFailed': 'Failed to send reset email',
  'auth.signInTitle': 'Sign in',
  'auth.signInDesc': 'Enter your email and password below to log into your account',
  'auth.noAccount': "Don't have an account?",
  'auth.signUp': 'Sign up',
  'auth.signUpTitle': 'Create an account',
  'auth.signUpDesc': 'Enter your email and password to create an account.',
  'auth.haveAccount': 'Already have an account?',
  'auth.signIn': 'Sign In',
  'auth.termsAgree': 'By creating an account, you agree to our',
  'auth.termsOfService': 'Terms of Service',
  'auth.and': 'and',
  'auth.privacyPolicy': 'Privacy Policy',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordDesc': 'Enter your registered email and we will send you a link to reset your password.',
  'auth.twoFactorTitle': 'Two-factor Authentication',
  'auth.twoFactorDesc': 'Please enter the authentication code. We have sent the authentication code to your email.',
  'auth.notReceived': "Haven't received it?",
  'auth.resendCode': 'Resend a new code',

  // Error pages
  'error.404': '404',
  'error.404Title': 'Oops! Page Not Found!',
  'error.404Desc': "It seems like the page you're looking for does not exist or might have been removed.",
  'error.500': '500',
  'error.500Title': 'Oops! Something went wrong',
  'error.500Desc': 'We apologize for the inconvenience. Please try again later.',
  'error.401': '401',
  'error.401Title': 'Unauthorized Access',
  'error.401Desc': 'Please log in with the appropriate credentials to access this resource.',
  'error.403': '403',
  'error.403Title': 'Access Forbidden',
  'error.403Desc': "You don't have necessary permission to view this resource.",
  'error.503': '503',
  'error.503Title': 'Website is under maintenance!',
  'error.503Desc': "The site is not available at the moment. We'll be back online shortly.",
  'error.goBack': 'Go Back',
  'error.backToHome': 'Back to Home',
  'error.learnMore': 'Learn more',

  // Theme settings
  'theme.title': 'Theme Settings',
  'theme.description': 'Adjust the appearance and layout to suit your preferences.',
  'theme.reset': 'Reset',
  'theme.resetAll': 'Reset all settings to default values',
  'theme.theme': 'Theme',
  'theme.system': 'System',
  'theme.light': 'Light',
  'theme.dark': 'Dark',
  'theme.themeDesc': 'Choose between system preference, light mode, or dark mode',
  'theme.sidebar': 'Sidebar',
  'theme.inset': 'Inset',
  'theme.floating': 'Floating',
  'theme.sidebarOption': 'Sidebar',
  'theme.sidebarDesc': 'Choose between inset, floating, or standard sidebar layout',
  'theme.layout': 'Layout',
  'theme.default': 'Default',
  'theme.compact': 'Compact',
  'theme.fullLayout': 'Full layout',
  'theme.layoutDesc': 'Choose between default expanded, compact icon-only, or full layout mode',
  'theme.direction': 'Direction',
  'theme.ltr': 'Left to Right',
  'theme.rtl': 'Right to Left',
  'theme.directionDesc': 'Choose between left-to-right or right-to-left site direction',

  // Practice/Study components
  'practice.answerSheet': 'Answer Sheet',
  'practice.settings': 'Settings',
  'practice.fontSize': 'Font size',
  'practice.fontSmall': 'small',
  'practice.fontNormal': 'normal',
  'practice.fontLarge': 'large',
  'practice.bookmark': 'Bookmark',
  'practice.correctCount': 'Correct count',
  'practice.wrongCount': 'Wrong count',
  'practice.answerCard': 'Answer Card',

  // Common components
  'common.search': 'Search',
  'common.typeCommand': 'Type a command or search...',
  'common.noResults': 'No results found.',
  'common.toggleTheme': 'Toggle theme',
  'common.skipToMain': 'Skip to Main',
  'common.selected': 'selected',
  'common.clearSelection': 'Clear selection',
  'common.rowsPerPage': 'Rows per page',
  'common.pageOf': 'Page {current} of {total}',
  'common.goToFirstPage': 'Go to first page',
  'common.goToPrevPage': 'Go to previous page',
  'common.goToNextPage': 'Go to next page',
  'common.goToLastPage': 'Go to last page',
  'common.filter': 'Filter...',
  'common.view': 'View',
  'common.toggleColumns': 'Toggle columns',
  'common.clearFilters': 'Clear filters',
  'common.pickDate': 'Pick a date',
  'common.comingSoon': 'Coming Soon!',
  'common.comingSoonDesc': 'This page has not been created yet. Stay tuned though!',
  'common.guestUser': 'Guest User',

  // Sign out dialog
  'signOut.title': 'Sign out',
  'signOut.description': 'Are you sure you want to sign out? You will need to sign in again to access your account.',
  'signOut.confirm': 'Sign out',
}

vi.mock('@/context/language-provider', () => ({
  useLanguage: () => ({
    language: 'en',
    defaultLanguage: 'en',
    setLanguage: vi.fn(),
    resetLanguage: vi.fn(),
    t: (key: string) => englishTranslations[key] ?? key,
  }),
  getLocalizedExplanation: (
    explanations: { en?: string; zh?: string; 'zh-TW'?: string; ja?: string } | undefined,
    _language: string
  ) => {
    if (!explanations) return ''
    return explanations.en || explanations.zh || explanations['zh-TW'] || explanations.ja || ''
  },
  LanguageProvider: ({ children }: { children: React.ReactNode }) => children,
}))
